### ISSUE TITLE
Where to find IP address of client

### ISSUE THREAD

**Issue by bosonno** [joeferner/node-http-mitm-proxy#101]
Where do I find the IP address of the client of the clientToProxyRequest?

**Comment by bosonno** [comment]
ctx.clientToProxyRequest.socket.remoteAddress

**Comment by felicienfrancois** [comment]
```javascript
ctx.clientToProxyRequest.connection.remoteAddress
```

http://stackoverflow.com/questions/8107856/how-to-determine-a-users-ip-address-in-node

**Comment by acaele** [comment]
Hi. This is not workiign for me.. Always returns 127.0.0.1

**Comment by binux** [comment]
`ctx.clientToProxyRequest.socket.remoteAddress` Is not actually the address of client when making HTTPS connections.

https://github.com/joeferner/node-http-mitm-proxy/blob/d7c9f373bcdbd79ffeea0af15fa411338aa5473a/lib/proxy.js#L372

**Comment by sweet-peach** [comment]
I'm not sure how useful this will be to someone else, but I encountered a task of determining a user's IP address, which turned out to be difficult due to the peculiarities of processing HTTPS requests. After extensive searching, I found a solution: when processing an HTTPS request through a proxy, a separate HTTPS server is created, allowing the modification of encrypted content. In this case, the onrequest event is activated, and special data is available for HTTPS requests. In the context of HTTPS, the context.clientToProxyRequest object contains information about the local HTTPS server, and client data is stored in context.connectRequest. Thanks to this, the user's IP address during HTTPS requests can be determined through context.connectRequest.socket.remoteAddress
