### ISSUE TITLE
SSL requests - certificate problem

### ISSUE THREAD

**Issue by escribileamauro** [joeferner/node-http-mitm-proxy#16]
Hi

I am having trouble with HTTS connections passing through the proxy. Its seems that somehow these do not validate against the self signed SSL keys. I am able to see that the proxy works fine if I manually make an exception in Firefox, but these should work without having to manually make an exception after adding the keys to the keychain. 

See below for the quests, I even tried to use "--cacert certificate" but it still fails. 

curl -v --proxy https://localhost:8080 https://google.com
* Rebuilt URL to: https://google.com/
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
* Establish HTTP proxy tunnel to google.com:443
> CONNECT google.com:443 HTTP/1.1
> Host: google.com:443
> User-Agent: curl/7.37.1
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 OK
< 
* Proxy replied OK to CONNECT request
* SSL certificate problem: Invalid certificate chain
* Closing connection 0
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

Thanks,
Mauro

**Comment by felicienfrancois** [comment]
To makes it work, you have to import the generated root certificate `ca.pem` in the `.http-mitm-proxy/certs` directory as a trusted autority.

### In firefox:
Options > Advanced > Certificates > Click on `Show Certificates` button
In the Autorities tab > Import > Select ca.pem > Check Allow certificate to authentify web sites > Click OK

The wording may not be accurate because my firefox is not in english.

**Comment by felicienfrancois** [comment]
Also, you may have ssl certificate cache issue when you toggle proxy settings

**Comment by VictorBjelkholm** [comment]
Instructions by @felicienfrancois seems to work fine. One issue I've found with Firefox though is that the certificate is only valid for one https site, not more. So once you used it on one site, it's invalid for the rest, since Firefox doesn't accept one certificates for multiple sites. Error seems to be `sec_error_reused_issuer_and_serial`
Bugzilla entry here: https://bugzilla.mozilla.org/show_bug.cgi?id=435013

**Comment by felicienfrancois** [comment]
@VictorBjelkholm each https site have a different certificate, generated at first access, issued by the same "FAKE" authority.
The `sec_error_reused_issuer_and_serial` error is due to when generating the certificate for a server, the `certificate serial number` is always set to the same value whereas it should be unique per certificate.

I just made a pull request to fix this: https://github.com/joeferner/node-http-mitm-proxy/pull/30
With this change, you should no longer get the issue (but you'll have to delete previously generated server keys and certificates from `.http-mitm-proxy/keys` and `.http-mitm-proxy/certs`.
Don't remove ca.pem, ca.private.key and ca.public.key otherwise you would have to reimport it to firefox after regen

**Comment by VictorBjelkholm** [comment]
@felicienfrancois Awesome!

Left a comment in PR before I saw your comment here, if it's as simple as advertised, it seems good. Thanks a lot for the fast fix!

**Comment by VictorBjelkholm** [comment]
Yes, working as advertised! Think you can close this issue @felicienfrancois

**Comment by Devhercule** [comment]
@felicienfrancois 
would it be possible not to generate a certificate for each domain? and to use the ca.pem for all sites?
like that:
```
proxy.onCertificateRequired = function(hostname, callback) {
  return callback(null, {
    keyFile: path.resolve('/ca/certs/', 'ca.private.key'),
    certFile: path.resolve('/ca/certs/', 'ca.pem')
  });
};
```
Thanks
