### ISSUE TITLE
SSL3_GET_CLIENT_HELLO no shared cipher

### ISSUE THREAD

**Issue by flippyhead** [joeferner/node-http-mitm-proxy#59]
I've set things up using the generated CA.perm as a trusted root CA. I see in the logs often errors like this: 

> W20160222-16:07:01.200(-3)? (STDERR) HTTPS_CLIENT_ERROR on : [Error: 140735123144704:error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher:../deps/openssl/openssl/ssl/s3_srvr.c:1436:

This seems to be related to problems with some kinds of web socket connections over SSL, though I'm not yet 100% clear on the association. It may be that all examples produce the error but https://github.com/joeferner/node-http-mitm-proxy/blob/master/examples/processFullResponseBody.js definitely does.

**Comment by felicienfrancois** [comment]
This error happens at the SSL negociation step between the client (i.e. the browser) and the proxy
At the SSL negociation step, the server (here the proxy) send a cipher suite (i.e. the list of accepted encryption algorythm) to the client. The client have to choose an encryption algorythm and then encrypt all next communication using it.
The "no shared cipher" error means the client supports none of the encryption algorythms proposed by the server. As a result, the connection connot be ssl encrypted.

The recommended and supported cipher suite have changed a lot over the past years due to security concerns.

This error may be due to:
- the server (i.e. proxy) cipher suite is obsolete
The proxy cipher suite is the [nodejs default](https://nodejs.org/api/tls.html#tls_modifying_the_default_tls_cipher_suite). It should be a "modern" cipher suite if your nodejs version is up-to-date
- The client (i.e. browser) cipher suite is obsolete
For example internet explorer 8 and before should no longer be used because all the supported ciphers are vulnerable. As a result such a browser would not be able to connect to the proxy or to any other server which is security aware.

You can test your browser cipher suite here: https://www.howsmyssl.com/ (test without the proxy ...)

You can probably fix it by [modifying the proxy cipher suite](https://nodejs.org/api/tls.html#tls_modifying_the_default_tls_cipher_suite)

**Comment by flippyhead** [comment]
OK excellent explanation thank you! I'm using this library along with Meteor which imposes a somewhat old version of node. Going to remove my dependency on Meteor so I can use a later version of node.
