### ISSUE TITLE
Why not support HTTP CONNECT METHOD?

### ISSUE THREAD

**Issue by flippyhead** [joeferner/node-http-mitm-proxy#63]
So that you can use the proxy for both HTTP and HTTPS traffic even if you don't do the cert re-generation dance.

As described [here](http://tools.ietf.org/rfc/rfc2817). Also, I believe [squid uses it](http://wiki.squid-cache.org/Features/HTTPS) correctly.

**Comment by felicienfrancois** [comment]
Actually, we're using the CONNECT method.
CONNECT is the method used to "connect" to the proxy and ask for a TLS tunnel to the destination host before making HTTPS request.
> the HTTP CONNECT method for establishing end-to-end tunnels across HTTP proxies

This has no relation with the cert regeneration dance.

From a [previous comment](https://github.com/joeferner/node-http-mitm-proxy/issues/50#issuecomment-170017409):

> node-http-mitm-proxy is a [MITM](https://en.wikipedia.org/wiki/Man-in-the-middle_attack) proxy. This means it have been designed to be able to read and alter the requests and responses, this is why it need to use a generated certificate to reencode altered content.
Standard proxies (like squid) and Content Filtering Solutions does not require this because they are only able to forward or not forward requests and responses, without being able to read all encrypted data nor altering it.
Technically, thoose kind of standard proxies can:
- Read hostname and methods of SSL requests but cannot read url, headers nor content of it
- Forward or cancel requests but cannot alter it.
- Read response content
- Forward or cancel response but cannot alter it or fake it.

> If you want to access more information from the request or being able to alter request or response, you must use a MITM proxy which have to decrypt and reencrypt requests and responses, with generated certificates.

**Comment by felicienfrancois** [comment]
So the answer is:
- we already use CONNECT Method
- the cert re-generation dance is required for being able to read and alter requests and responses, which is this project is designed to

=> Closing
