### ISSUE TITLE
Do not close the HTTPS servers.

### ISSUE THREAD

**Issue by therifler** [joeferner/node-http-mitm-proxy#64]
Hey, as long as the module is running in the system, I see a growing number of open ports. How to clean unnecessary open HTTPS servers?

I tried this way on ctx.onResponseEnd:
```
(Object.keys(proxy.sslServers)).forEach(function (srvName) {
	if (proxy.sslServers[srvName].server._connections === 0 && !proxy.sslServers[srvName].server._handle.reading && proxy.sslServers[srvName].server._handle.writeQueueSize === 0) {
		console.log('Can: ', proxy.sslServers[srvName].server);
		proxy.sslServers[srvName].server.close();
		delete proxy.sslServers[srvName];
		console.log('HTTPS Server: "' + srvName.yellow + '" closed.');
	} else {
		console.log('Cannot: ', proxy.sslServers[srvName].server);
	}
});
```
Did not work. Proxy client loses the connection and make mistakes. Please help.

**Comment by felicienfrancois** [comment]
This may be due to race condition. With your code you may close an https server which have been selected to be used for another resquest but with the connection not yet etablished.

Avoiding race condition would require changes in the proxy code.

Another solution to your issue may be the [forceSNI option](https://github.com/joeferner/node-http-mitm-proxy#proxylisten) (just pushed to HEAD yesterday)
When enabled, there is only one https server started to handle all hosts. this is made possible through using [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication).

**Comment by therifler** [comment]
@felicienfrancois thanks a lot! It works great :+1:
