### ISSUE TITLE
Failed to load resource: The network connection was lost.

### ISSUE THREAD

**Issue by flippyhead** [joeferner/node-http-mitm-proxy#65]
I've got a basic HTTP/HTTPS proxy running:

```javascript
var Proxy = require('http-mitm-proxy');
var proxy = Proxy();

proxy.onError( (ctx, err, errorKind) => {
  var url = (ctx && ctx.clientToProxyRequest) ? ctx.clientToProxyRequest.url : '';
  console.error(errorKind + ' on ' + url + ':', err);
});

proxy.use(Proxy.gunzip);

proxy.listen({port: 8089, sslCaDir: "/Users/peter/Development/fetching-proxy/certs"});
```

I notice that Safari (possibly other browsers) frequently show this kind of error in the console for JS and CSS assets:

> Failed to load resource: The network connection was lost.

I'm not sure they are related, but the node console also has many:

> HTTPS_CLIENT_ERROR on : { [Error: socket hang up] code: 'ECONNRESET' }

and 

> PROXY_TO_SERVER_REQUEST_ERROR on /510080801/: { [Error: connect ETIMEDOUT 31.13.85.8:443]

Needless to say this causes most websites to have trouble loading.

Thank you!

**Comment by felicienfrancois** [comment]
Thank you for this report.

Personally, i sometimes have thoose errors on Safari even without proxy. Safari probably have a low request timeout and cancel too long requests before the end.

With the proxy, the request takes inevitably longer to be answered and so the rate of cancelled request is higher.

But they are still areas for improvement.
We're currently working on a few:
- Start only one internal HTTPS Server instead of one per host. _Pushed yesterday, you can enable this on HEAD using [forceSNI option](https://github.com/joeferner/node-http-mitm-proxy#proxylisten))_
- Generate wilcard certificates by default in order to generate less certificates _(WIP)_
- Enable HTTP/2 support _(WIP)_

But there are a lot more things we could do.
Any help is welcomed to:
- Discuss about areas for improvement
- Benchmark / Test / Identify the perf issues
- Fix issues (PR welcome)
- Update documentation (PR welcome)

**Comment by felicienfrancois** [comment]
Here another discussion about performance: https://github.com/joeferner/node-http-mitm-proxy/issues/39
