### ISSUE TITLE
Gunzip throw error on partial chunks

### ISSUE THREAD

**Issue by shaunlebron** [joeferner/node-http-mitm-proxy#81]
Steps to reproduce:

1. `node examples/processFullResponseBody.js`
2. Open Chrome (with proxy setup)
3. Navigate to <http://humblebundle.com> (should succeed)
4. Refresh page, and see console output for exception below.

```
$ node examples/processFullResponseBody.js
listening on 8081

...some lines removed, everything below is after refresh...

starting server for humble.pubnub.com
https server started for humble.pubnub.com on 56619
starting server for www.humblebundle.com
https server started for www.humblebundle.com on 56888
starting server for humblebundle-a.akamaihd.net
https server started for humblebundle-a.akamaihd.net on 56958
starting server for checkout.stripe.com
https server started for checkout.stripe.com on 56969
starting server for www.youtube.com
https server started for www.youtube.com on 56995
starting server for connect.facebook.net
https server started for connect.facebook.net on 56999
starting server for apis.google.com
https server started for apis.google.com on 57005
starting server for platform.twitter.com
https server started for platform.twitter.com on 57008
starting server for chart.googleapis.com
https server started for chart.googleapis.com on 57012
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:363:17)
```

**Comment by felicienfrancois** [comment]
On humblebundle.com, this error is triggered by the request to get facebook connect script and it only happen when refreshing. I suppose it may happen on any page that includes this script.

This error is due to the server sending a partial or invalid gzipped chunk on refresh.
In don't know if it's a normal behavior or not.

In the meantime, I have made a PR (#83) to handles errors from request and response filters.
With this fix the error is logged instead of breaking the proxy and the page display normally.

**Comment by shaunlebron** [comment]
Great find, thanks @felicienfrancois! 👍 I tried it on latest master, and everything works great.
