### ISSUE TITLE
Add linting rules

### ISSUE THREAD

**Issue by gajus** [joeferner/node-http-mitm-proxy#82]
It is extremely hard to contribute to the codebase when there are no linting rules/ code style is inconsistent between files.

I suggest to use one of the existing style guides, https://github.com/dustinspecker/awesome-eslint#configs:

* Canonical is the most strict of them all (I am biased though, since it is the package that I maintain).
* AirBnb is the most popular.
* Standard while popular, is very loose

@joeferner Do you agree that linting rules need to be added? Do you have preference for which style guide to use?

**Comment by felicienfrancois** [comment]
This is a good idea.
I think we should not go on a too strict style guide because:
- it may fear people that would like to contribute
- It would add unuseful extra work, at initial step and when contributing or when reviewing/rewriting PRs

AirBnb seems to be good enough to improve our code quality and readability.

PR are welcome

**Comment by gajus** [comment]
I have gone with a different library. Re-open this issue if you'd like to take it over.
